enum_discrim_align_threshold = 20
fn_single_line = true
format_macro_matchers = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
struct_lit_single_line = false
use_field_init_shorthand = true
